### ISSUE TITLE
Assembler message "Value out of range"

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#35]
osboxes@osboxes:~/espeak-source/src/amiga$ /home/osboxes/opt/m68k-amigaos_gcc6/bin/m68k-amigaos-gcc  -Os   -c   val_out_of_range.cpp
/tmp/cci47R1l.s: Assembler messages:
/tmp/cci47R1l.s:434: Error: value out of range
/tmp/cci47R1l.s:434: Error: value of 1406 too large for field of 1 bytes at 1371

* There is no error if compiled without "-Os"
* Compilation shows no error if compiled with gcc2.95.3

[val_out_of_range.cpp.gz](https://github.com/bebbo/amigaos-cross-toolchain/files/1167588/val_out_of_range.cpp.gz)

**Comment by bebbo** [comment]
The error results from
```
	move.w .L85(pc,d2.l),d0
```
and the label is to far away.

I'm not sure if this can be easily fixed. Use a different optimizing level or compile for 68020+ as a workaround meanwhile.

You can also try to disable specific gcc optimizers, but I assume that this bug is in pass_rtl_hoist which is only invoked if optimizing for size,

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
Tested first with old gcc6 version (commit d4e28f9fc141b7d0f6f450379f47123e0ea45927 from Wed Oct 11) again. Fails as described in issue.

The tested with current version and now my program compiles completely with -Os.
Problem seems to be solved at least for -Os.
