### ISSUE TITLE
-mhard-float causes compiler issues together with -Os.

### ISSUE THREAD

**Issue by MBeijer** [bebbo/amigaos-cross-toolchain#49]
-mhard-float causes compiler issues together with optimizations. 
-msoft-float, -mhard-float and -m68881, without optimizations causes applications to crash.

Compile flags for hard float with optimizations:

> cppflags = "-g -m68040 -mhard-float -fomit-frame-pointer -fno-exceptions -Os -noixemul -I/opt/m68k-amigaos/m68k-amigaos/sys-include -I/opt/m68k-amigaos/include -I/opt/m68k-amigaos/include/SDL ",

> ../src/fx/ParticleBlobs.cpp: In constructor ‘ParticleBlobs::ParticleBlobs(int, int)’:
> ../src/fx/ParticleBlobs.cpp:100:1: error: unrecognizable insn:
>  }
>  ^
> (insn 237 150 219 (set (mem:SI (post_inc:SI (reg/f:SI 8 a0 [orig:112 _139 ] [112])) [4 _139->pos.x+0 S4 A16])
>         (fix:SI (fix:DF (reg:DF 16 fp0 [183])))) -1
>      (nil))
> ../src/fx/ParticleBlobs.cpp:100:1: internal compiler error: in extract_insn, at recog.c:2287
> 0xd7c163 _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:108
> 0xd7c1a4 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/rtl-error.c:116
> 0xd300bb extract_insn(rtx_insn*)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/recog.c:2287
> 0xd2fd85 extract_insn_cached(rtx_insn*)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/recog.c:2178
> 0xa9c151 cleanup_subreg_operands(rtx_insn*)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:3106
> 0xa9bb44 final_scan_insn(rtx_insn*, _IO_FILE*, int, int, int*)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2907
> 0xa99fc0 final(rtx_insn*, _IO_FILE*, int)
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:2045
> 0xa9e7a6 rest_of_handle_final
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4448
> 0xa9e9a4 execute
>         /home/marlon/amigaos-cross-toolchain/submodules/gcc-6/gcc/final.c:4523
> Please submit a full bug report,
> with preprocessed source if appropriate.
> Please include the complete backtrace with any bug report.
> See <http://gcc.gnu.org/bugs.html> for instructions.
> fx.make:417: recipe for target 'obj/m68k-amigaos/Release/fx/ParticleBlobs.o' failed
> make[1]: *** [obj/m68k-amigaos/Release/fx/ParticleBlobs.o] Error 1
> Makefile:32: recipe for target 'fx' failed
> make: *** [fx] Error 2
>

**Comment by Samuel-DEVULDER** [comment]
I got the same issue here with the latest source compiled under cygwin64:
---------------------8<------------------------------------------------------------------
$  /opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b.exe -v
Utilisation des specs internes.
COLLECT_GCC=/opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b
COLLECT_LTO_WRAPPER=/opt/m68k-amigaos/libexec/gcc/m68k-amigaos/6.3.1b/lto-wrapper.exe
Cible : m68k-amigaos
Configuré avec: /home/Samuel/amigaos-cross-toolchain/submodules/gcc-6/configure --prefix=/opt/m68k-amigaos --infodir=/opt/m68k-amigaos/m68k-amigaos/info --mandir=/opt/m68k-amigaos/share/man --prefix=/opt/m68k-amigaos --prefix=/opt/m68k-amigaos --target=m68k-amigaos --enable-languages=c,c++,objc --enable-version-specific-runtime-libs --disable-libssp --with-headers=/home/Samuel/amigaos-cross-toolchain/.build-m68k/sources/ixemul-48.2/include
Modèle de thread: single
gcc version 6.3.1b 20171123-203556 (GCC)

$  /opt/m68k-amigaos/bin/m68k-amigaos-gcc-6.3.1b.exe -m68881 -m68030 -O -c r_alias_crash_gcc6.c -o r_alias.o
r_alias_float.c: Dans la fonction « R_AliasCheckBBox »:
r_alias_float.c:227:1: erreur interne du compilateur : Segmentation fault
 }
 ^
Veuillez soumettre un rapport d’anomalies complet,
avec la sortie du préprocesseur si nécessaire.
Voir <http://gcc.gnu.org/bugs.html> pour les instructions.
---------------------8<------------------------------------------------------------------

The message is in french, but is basically says "internal compiler error" caused by a seg-fault. There is other details.

Without -O it compiles fine.

The code to test is available here: https://pastebin.com/ma096iBs (gcc -E output, should compile "out of the box").

**Comment by bebbo** [comment]
please retest

**Comment by Samuel-DEVULDER** [comment]
I've tested with `gcc version 6.3.1b 20171126-162846 (GCC)` and the compiler doesn't crash anymore.

**Comment by MBeijer** [comment]
Works for me as well.
