### ISSUE TITLE
SDL 1.2 fails compiling

### ISSUE THREAD

**Issue by tehKaiN** [bebbo/amigaos-cross-toolchain#71]
Recently I've tried to compile SDL from here: https://github.com/AmigaPorts/libSDL12 using latest commit's toolchain. Don't know who's really to blame, and  that repo has issues disabled, so I'll post it here.

I've had following problem:

```
video/amigaos/SDL_cgxvideo.c:40:41: fatal error: cybergraphics/cybergraphics.h: No such file or directory
```

I've compiled all external libs, and include exists, but on `cybergraphx/cybergraphics.h` path. I don't really use it so don't know which path is correct one. Anyway solved it by duplicating dir and renaming it.

Also I've had problem with vasm - their makefile calls `vasmm68k_mot` directly which for me was not found - your toolchain only has `vasm` script under bin and proper executable under `m68k-amigaos/bin`. Solved it by changing PATH, but dunno what is the reason to have two bin directories.

**Comment by MBeijer** [comment]
Okay, I'm partly responsible for the libSDL12 repo. The issue lies with
that for some reason the cybergraphics location has been switched between
being named cybergraphx to cybergaphics and vice versa. If you use
http://github.com/bebbo/amiga-gcc instead of this repo, the SDL is
installed and included in that toolchain. Consider this toolchain sort of
deprecated. This one uses basically the same stuff as the new one, except
the new one includes more.

**Comment by MBeijer** [comment]
And there, opened up issues for the libSDL12 repo. Didn't even notice it was disabled.

**Comment by bebbo** [comment]
should be fixed - if not open an issue in amiga-gcc
